class PostsController < ApplicationController
  def index
    @posts = [
      {titulo: 'Primer post', contenido: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper bibendum sem sit amet molestie. Maecenas sagittis pretium risus lobortis mattis. In porta erat a ante blandit faucibus. Etiam sed pharetra dui. Praesent ac lectus eu elit dapibus condimentum porttitor in nulla. Morbi a est diam. Curabitur pharetra ligula mi, eu sagittis eros porta eu. Maecenas lacinia mattis dolor, nec vulputate lacus malesuada ut. Nunc interdum est eget mattis luctus. In a accumsan odio. Vestibulum velit neque, lobortis non odio sed, placerat cursus nisi. Duis eleifend nisi lorem, sit amet tincidunt ex pharetra scelerisque. Fusce vulputate, dui ut sollicitudin faucibus, dolor lectus ultricies augue, et accumsan ligula purus id enim. Praesent elementum porta urna ac dictum. Proin egestas, elit eu bibendum dictum, erat ante tempor mi, facilisis ullamcorper neque diam vel est. Quisque vehicula, turpis eu iaculis pharetra, arcu sapien condimentum magna, eget vestibulum ipsum est ut magna. '},
      {titulo: 'Segundo post', contenido: 'Sed consequat luctus enim pellentesque faucibus. Nunc euismod euismod ipsum id sollicitudin. Vestibulum porta dui nec ultricies elementum. Etiam dictum libero id purus faucibus faucibus. Ut ut augue non est tincidunt sodales nec sed nisl. Aenean sed purus odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id velit vitae sem hendrerit malesuada. Vestibulum mattis leo vel arcu iaculis, eget placerat sapien rhoncus. '},
      {titulo: 'Tercer post', contenido: '  Cras metus massa, egestas at pellentesque sed, venenatis vel tellus. In ultrices nisl consequat imperdiet facilisis. Praesent lobortis diam non augue facilisis, in lobortis odio venenatis. In at dignissim massa, eget ullamcorper nibh. Integer et facilisis arcu. In at elit mollis quam tempor elementum vel ut tortor. Aliquam quis libero justo. Aenean euismod molestie auctor. Nunc ac ante eget nulla vehicula sagittis nec a orci. Quisque eu orci vulputate, scelerisque elit in, ornare risus. Nunc et nulla sit amet augue ullamcorper auctor. Maecenas eleifend varius sem, ac facilisis leo. Nulla est magna, vehicula vel leo ut, maximus consectetur metus. Sed purus mauris, porttitor quis ullamcorper nec, condimentum a lorem. Integer aliquam justo quis nisl finibus, id finibus orci varius.  '},
      {titulo: 'Cuarto post', contenido: ' Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas tristique, metus sit amet dictum maximus, dolor felis congue ligula, non eleifend mauris tortor ac turpis. Vivamus id magna non erat aliquet tristique et ac dolor. Aliquam porta elementum enim non molestie. Ut et ipsum porta neque consectetur interdum. Aenean dapibus et diam at vestibulum. Ut iaculis magna feugiat est dictum, in lacinia mi interdum. Maecenas diam est, viverra semper neque quis, feugiat facilisis neque. Aenean egestas ut odio sed facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;  '},
      {titulo: 'Quinto post', contenido: '  Aliquam varius bibendum eros, vel rhoncus lacus bibendum eget. Pellentesque lacinia, eros quis tincidunt gravida, tortor augue vestibulum risus, vitae facilisis nibh tellus non velit. Sed pulvinar nec mi nec convallis. Quisque congue lobortis congue. Nam orci augue, consectetur non risus ut, viverra egestas turpis. Morbi porttitor nulla orci, elementum blandit felis luctus non. Suspendisse sit amet nunc eget justo facilisis porta auctor id est. Nunc placerat, orci quis hendrerit ullamcorper, massa nulla dictum nisl, a sodales orci nulla ut risus. Sed finibus sapien augue, in scelerisque dolor tempus a. Mauris ultrices consequat rutrum. Nam ut sodales justo, vel ullamcorper arcu. '},
      {titulo: 'Sexto post', contenido: '   Sed consequat luctus enim pellentesque faucibus. Nunc euismod euismod ipsum id sollicitudin. Vestibulum porta dui nec ultricies elementum. Etiam dictum libero id purus faucibus faucibus. Ut ut augue non est tincidunt sodales nec sed nisl. Aenean sed purus odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id velit vitae sem hendrerit malesuada. Vestibulum mattis leo vel arcu iaculis, eget placerat sapien rhoncus. '},
    ]
  end

  def show
    @posts = [
      {titulo: 'Primer post', contenido: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper bibendum sem sit amet molestie. Maecenas sagittis pretium risus lobortis mattis. In porta erat a ante blandit faucibus. Etiam sed pharetra dui. Praesent ac lectus eu elit dapibus condimentum porttitor in nulla. Morbi a est diam. Curabitur pharetra ligula mi, eu sagittis eros porta eu. Maecenas lacinia mattis dolor, nec vulputate lacus malesuada ut. Nunc interdum est eget mattis luctus. In a accumsan odio. Vestibulum velit neque, lobortis non odio sed, placerat cursus nisi. Duis eleifend nisi lorem, sit amet tincidunt ex pharetra scelerisque. Fusce vulputate, dui ut sollicitudin faucibus, dolor lectus ultricies augue, et accumsan ligula purus id enim. Praesent elementum porta urna ac dictum. Proin egestas, elit eu bibendum dictum, erat ante tempor mi, facilisis ullamcorper neque diam vel est. Quisque vehicula, turpis eu iaculis pharetra, arcu sapien condimentum magna, eget vestibulum ipsum est ut magna. '},
      {titulo: 'Segundo post', contenido: 'Sed consequat luctus enim pellentesque faucibus. Nunc euismod euismod ipsum id sollicitudin. Vestibulum porta dui nec ultricies elementum. Etiam dictum libero id purus faucibus faucibus. Ut ut augue non est tincidunt sodales nec sed nisl. Aenean sed purus odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id velit vitae sem hendrerit malesuada. Vestibulum mattis leo vel arcu iaculis, eget placerat sapien rhoncus. '},
      {titulo: 'Tercer post', contenido: '  Cras metus massa, egestas at pellentesque sed, venenatis vel tellus. In ultrices nisl consequat imperdiet facilisis. Praesent lobortis diam non augue facilisis, in lobortis odio venenatis. In at dignissim massa, eget ullamcorper nibh. Integer et facilisis arcu. In at elit mollis quam tempor elementum vel ut tortor. Aliquam quis libero justo. Aenean euismod molestie auctor. Nunc ac ante eget nulla vehicula sagittis nec a orci. Quisque eu orci vulputate, scelerisque elit in, ornare risus. Nunc et nulla sit amet augue ullamcorper auctor. Maecenas eleifend varius sem, ac facilisis leo. Nulla est magna, vehicula vel leo ut, maximus consectetur metus. Sed purus mauris, porttitor quis ullamcorper nec, condimentum a lorem. Integer aliquam justo quis nisl finibus, id finibus orci varius.  '},
      {titulo: 'Cuarto post', contenido: ' Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas tristique, metus sit amet dictum maximus, dolor felis congue ligula, non eleifend mauris tortor ac turpis. Vivamus id magna non erat aliquet tristique et ac dolor. Aliquam porta elementum enim non molestie. Ut et ipsum porta neque consectetur interdum. Aenean dapibus et diam at vestibulum. Ut iaculis magna feugiat est dictum, in lacinia mi interdum. Maecenas diam est, viverra semper neque quis, feugiat facilisis neque. Aenean egestas ut odio sed facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;  '},
      {titulo: 'Quinto post', contenido: '  Aliquam varius bibendum eros, vel rhoncus lacus bibendum eget. Pellentesque lacinia, eros quis tincidunt gravida, tortor augue vestibulum risus, vitae facilisis nibh tellus non velit. Sed pulvinar nec mi nec convallis. Quisque congue lobortis congue. Nam orci augue, consectetur non risus ut, viverra egestas turpis. Morbi porttitor nulla orci, elementum blandit felis luctus non. Suspendisse sit amet nunc eget justo facilisis porta auctor id est. Nunc placerat, orci quis hendrerit ullamcorper, massa nulla dictum nisl, a sodales orci nulla ut risus. Sed finibus sapien augue, in scelerisque dolor tempus a. Mauris ultrices consequat rutrum. Nam ut sodales justo, vel ullamcorper arcu. '},
      {titulo: 'Sexto post', contenido: '   Sed consequat luctus enim pellentesque faucibus. Nunc euismod euismod ipsum id sollicitudin. Vestibulum porta dui nec ultricies elementum. Etiam dictum libero id purus faucibus faucibus. Ut ut augue non est tincidunt sodales nec sed nisl. Aenean sed purus odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id velit vitae sem hendrerit malesuada. Vestibulum mattis leo vel arcu iaculis, eget placerat sapien rhoncus. '},
    ]
  end
end
